name: ${project.artifactId}
main: ${package}.bukkit.${project.artifactId}Bukkit
version: ${project.version}
author: ${developer}
depend: [KaisCommons]

commands:
   uuidprovider:
      description: UUIDProvider commands

permissions:
    ${project.artifactId}.manage:
        description: Manage ${project.artifactId}
        default: op
