name: ${project.artifactId}
main: ${package}.${project.artifactId}
version: ${project.version}
author: KaiNoMood

commands:
   uuidprovider:
      description: UUIDProvider commands

permissions:
    ${project.artifactId}.manage:
        description: Manage ${project.artifactId}
        default: op
